# GKE Workload Identity Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beatsight-backend-sa
  namespace: beatsight
  annotations:
    iam.gke.io/gcp-service-account: beatsight-sql@beatsight.iam.gserviceaccount.com
