import React from 'react';
import clsx from 'clsx';
import Link from '@docusaurus/Link';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import Layout from '@theme/Layout';
import styles from './index.module.css';

function HomepageHeader() {
    const { siteConfig } = useDocusaurusContext();
    return (
        <header className={clsx('hero', styles.heroBanner)}>
            <div className="container">
                <div className={styles.heroContent}>
                    <h1 className={styles.heroTitle}>
                        <span className={styles.heroTitleGradient}>BeatSight</span> Documentation
                    </h1>
                    <p className={styles.heroSubtitle}>
                        Learn how to use AI-powered drum transcription to master any song
                    </p>
                    <div className={styles.buttons}>
                        <Link
                            className={clsx('button', styles.primaryButton)}
                            to="/docs/intro">
                            Get Started →
                        </Link>
                        <Link
                            className={clsx('button', styles.secondaryButton)}
                            to="/docs/api">
                            API Reference
                        </Link>
                    </div>
                </div>
            </div>
        </header>
    );
}

const features = [
    {
        title: 'Quick Setup',
        icon: '🚀',
        description: 'Get BeatSight running in minutes. Our desktop app works on Windows, macOS, and Linux with automatic updates.',
        link: '/docs/getting-started/installation',
    },
    {
        title: 'AI Transcription',
        icon: '🤖',
        description: 'Upload any song and get accurate drum notation generated by our state-of-the-art neural network.',
        link: '/docs/intro',
    },
    {
        title: 'Practice Tools',
        icon: '🥁',
        description: 'Slow down songs, loop sections, isolate drums, and follow along with visual notation.',
        link: '/docs/getting-started/practice-mode',
    },
    {
        title: 'API Access',
        icon: '⚡',
        description: 'Integrate BeatSight into your own applications with our comprehensive REST API.',
        link: '/docs/api',
    },
    {
        title: 'Beatmap Format',
        icon: '📄',
        description: 'Learn about our .bs beatmap format and how to create, edit, and share beatmaps.',
        link: '/docs/api/beatmap-format',
    },
    {
        title: 'Community',
        icon: '🤝',
        description: 'Join our community of drummers and transcribers. Contribute corrections and share knowledge.',
        link: 'https://github.com/rosacry/BeatSight/discussions',
    },
];

function Feature({ title, icon, description, link }) {
    return (
        <div className={styles.featureCard}>
            <div className={styles.featureIcon}>{icon}</div>
            <h3 className={styles.featureTitle}>{title}</h3>
            <p className={styles.featureDescription}>{description}</p>
            <Link to={link} className={styles.featureLink}>
                Learn more →
            </Link>
        </div>
    );
}

function HomepageFeatures() {
    return (
        <section className={styles.features}>
            <div className="container">
                <h2 className={styles.sectionTitle}>Everything You Need</h2>
                <div className={styles.featureGrid}>
                    {features.map((props, idx) => (
                        <Feature key={idx} {...props} />
                    ))}
                </div>
            </div>
        </section>
    );
}

function HomepageCTA() {
    return (
        <section className={styles.cta}>
            <div className="container">
                <div className={styles.ctaContent}>
                    <h2 className={styles.ctaTitle}>Ready to Start?</h2>
                    <p className={styles.ctaDescription}>
                        Download BeatSight and transform any song into drum practice material in minutes.
                    </p>
                    <div className={styles.ctaButtons}>
                        <Link
                            className={clsx('button', styles.primaryButton)}
                            to="https://beatsight.io">
                            Go to App
                        </Link>
                        <Link
                            className={clsx('button', styles.secondaryButton)}
                            to="https://github.com/rosacry/BeatSight">
                            View on GitHub
                        </Link>
                    </div>
                </div>
            </div>
        </section>
    );
}

export default function Home() {
    const { siteConfig } = useDocusaurusContext();
    return (
        <Layout
            title="Documentation"
            description="BeatSight documentation - Learn how to use AI-powered drum transcription">
            <HomepageHeader />
            <main>
                <HomepageFeatures />
                <HomepageCTA />
            </main>
        </Layout>
    );
}
