"""
Community Contribution Import Utility

This module imports approved community contributions from the BeatSight
backend into training datasets. It converts the contribution format
to the standard training sample format used by the classifier.

Usage:
    from training.import_contributions import ContributionImporter
    
    importer = ContributionImporter(
        manifest_path="contributions_manifest.json",
        output_dir="training_data/community"
    )
    importer.import_samples()
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass


@dataclass
class ContributionSample:
    """Represents a single contribution sample."""
    id: str
    map_version_id: str
    onset_time_ms: int
    correction_type: str
    original_component: Optional[str]
    original_confidence: Optional[float]
    corrected_component: Optional[str]
    corrected_time_ms: Optional[int]
    corrected_velocity: Optional[int]
    weight: float = 1.0


class ContributionImporter:
    """
    Imports community contributions into training format.
    
    The importer reads contribution manifests generated by the backend
    and creates training-compatible sample records that can be used
    to fine-tune the drum classifier.
    """
    
    # Mapping from contribution component names to training labels
    COMPONENT_MAP = {
        "kick": "kick",
        "snare": "snare_center",
        "snare-rim": "snare_rimshot",
        "snare-cross": "snare_cross_stick",
        "hi-hat": "hihat_closed",
        "hi-hat-open": "hihat_open",
        "hi-hat-pedal": "hihat_pedal",
        "ride": "ride_bow",
        "ride-bell": "ride_bell",
        "crash": "crash",
        "china": "china",
        "splash": "splash",
        "tom": "tom_mid",
        "tom-high": "tom_high",
        "tom-low": "tom_low",
        "floor-tom": "tom_low",
    }
    
    def __init__(
        self,
        manifest_path: Optional[str] = None,
        output_dir: str = "training_data/community",
    ):
        """
        Initialize the importer.
        
        Args:
            manifest_path: Path to contributions manifest JSON
            output_dir: Directory for output training data
        """
        self.manifest_path = Path(manifest_path) if manifest_path else None
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        self.imported_count = 0
        self.skipped_count = 0
        self.errors: List[str] = []
    
    def load_manifest(self, manifest_path: Optional[str] = None) -> Dict[str, Any]:
        """Load a contributions manifest from disk."""
        path = Path(manifest_path) if manifest_path else self.manifest_path
        if not path or not path.exists():
            raise FileNotFoundError(f"Manifest not found: {path}")
        
        with open(path) as f:
            return json.load(f)
    
    def import_from_manifest(
        self,
        manifest: Dict[str, Any],
        min_weight: float = 0.5,
    ) -> Tuple[int, int]:
        """
        Import samples from a manifest dictionary.
        
        Args:
            manifest: Parsed manifest dictionary
            min_weight: Minimum weight threshold for import
            
        Returns:
            Tuple of (imported_count, skipped_count)
        """
        samples = manifest.get("samples", [])
        batch_id = manifest.get("batch_id", "unknown")
        
        # Create batch output directory
        batch_dir = self.output_dir / batch_id
        batch_dir.mkdir(exist_ok=True)
        
        imported = 0
        skipped = 0
        training_samples = []
        
        for sample_data in samples:
            try:
                sample = self._parse_sample(sample_data)
                
                # Skip low-weight samples
                if sample.weight < min_weight:
                    skipped += 1
                    continue
                
                # Convert to training format
                training_sample = self._to_training_format(sample, batch_id)
                if training_sample:
                    training_samples.append(training_sample)
                    imported += 1
                else:
                    skipped += 1
                    
            except Exception as e:
                self.errors.append(f"Error processing sample {sample_data.get('id', '?')}: {e}")
                skipped += 1
        
        # Write training samples
        output_file = batch_dir / "samples.json"
        with open(output_file, "w") as f:
            json.dump({
                "batch_id": batch_id,
                "source": "community_contributions",
                "imported_at": datetime.utcnow().isoformat() + "Z",
                "sample_count": len(training_samples),
                "manifest_version": manifest.get("version", "unknown"),
                "samples": training_samples,
            }, f, indent=2)
        
        # Write import metadata
        meta_file = batch_dir / "import_meta.json"
        with open(meta_file, "w") as f:
            json.dump({
                "batch_id": batch_id,
                "imported_at": datetime.utcnow().isoformat() + "Z",
                "imported_count": imported,
                "skipped_count": skipped,
                "min_weight_threshold": min_weight,
                "errors": self.errors,
            }, f, indent=2)
        
        self.imported_count += imported
        self.skipped_count += skipped
        
        return imported, skipped
    
    def _parse_sample(self, data: Dict[str, Any]) -> ContributionSample:
        """Parse a sample from manifest data."""
        original = data.get("original", {})
        corrected = data.get("corrected", {})
        
        return ContributionSample(
            id=data["id"],
            map_version_id=data["map_version_id"],
            onset_time_ms=data["onset_time_ms"],
            correction_type=data["correction_type"],
            original_component=original.get("component"),
            original_confidence=original.get("confidence"),
            corrected_component=corrected.get("component"),
            corrected_time_ms=corrected.get("time_ms"),
            corrected_velocity=corrected.get("velocity"),
            weight=data.get("weight", 1.0),
        )
    
    def _to_training_format(
        self,
        sample: ContributionSample,
        batch_id: str,
    ) -> Optional[Dict[str, Any]]:
        """
        Convert a contribution sample to training format.
        
        Training samples need:
        - A label (component name)
        - Reference to audio/beatmap
        - Onset time
        - Optional confidence weighting
        
        Returns:
            Training sample dict or None if cannot be converted
        """
        # Only component changes and additions give us clear labels
        if sample.correction_type not in ("component_change", "note_addition"):
            return None
        
        # Get the corrected component (the truth)
        component = sample.corrected_component
        if not component:
            return None
        
        # Map to training label
        training_label = self.COMPONENT_MAP.get(component, component)
        
        return {
            "id": f"contrib_{sample.id}",
            "source": "community_contribution",
            "batch_id": batch_id,
            "map_version_id": sample.map_version_id,
            "onset_time_ms": sample.corrected_time_ms or sample.onset_time_ms,
            "label": training_label,
            "original_label": self.COMPONENT_MAP.get(
                sample.original_component or "", sample.original_component
            ),
            "original_confidence": sample.original_confidence,
            "weight": sample.weight,
            "correction_type": sample.correction_type,
        }
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get import statistics."""
        return {
            "total_imported": self.imported_count,
            "total_skipped": self.skipped_count,
            "error_count": len(self.errors),
            "errors": self.errors[:10],  # First 10 errors
        }


def import_contributions(
    manifest_path: str,
    output_dir: str = "training_data/community",
    min_weight: float = 0.5,
) -> Dict[str, Any]:
    """
    Convenience function to import contributions from a manifest file.
    
    Args:
        manifest_path: Path to the manifest JSON
        output_dir: Output directory for training data
        min_weight: Minimum weight threshold
        
    Returns:
        Import statistics dictionary
    """
    importer = ContributionImporter(output_dir=output_dir)
    manifest = importer.load_manifest(manifest_path)
    
    imported, skipped = importer.import_from_manifest(manifest, min_weight)
    
    stats = importer.get_statistics()
    print(f"Import complete: {imported} imported, {skipped} skipped")
    
    return stats


if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Import community contributions into training data"
    )
    parser.add_argument(
        "manifest",
        help="Path to contributions manifest JSON"
    )
    parser.add_argument(
        "--output-dir",
        default="training_data/community",
        help="Output directory for training data"
    )
    parser.add_argument(
        "--min-weight",
        type=float,
        default=0.5,
        help="Minimum weight threshold (default: 0.5)"
    )
    
    args = parser.parse_args()
    
    stats = import_contributions(
        args.manifest,
        args.output_dir,
        args.min_weight,
    )
    
    print("\nImport Statistics:")
    print(f"  Imported: {stats['total_imported']}")
    print(f"  Skipped: {stats['total_skipped']}")
    print(f"  Errors: {stats['error_count']}")
