#!/usr/bin/env python3
"""
Apply Label Corrections to Dataset

Takes the corrections generated by clean_label_noise.py and creates
a new dataset with corrected labels.

Usage:
    python apply_label_corrections.py \
        --corrections label_corrections/train_label_corrections.npz \
        --dataset F:/datasets/prod_v5_cleaned \
        --split train \
        --output F:/datasets/prod_v5_fixed

Or apply to both splits:
    python apply_label_corrections.py \
        --corrections-dir label_corrections \
        --dataset F:/datasets/prod_v5_cleaned \
        --output F:/datasets/prod_v5_fixed
"""

import argparse
import json
import shutil
import sys
from pathlib import Path

import numpy as np

# Add ai-pipeline to path
AI_PIPELINE_ROOT = Path(__file__).resolve().parents[2]
if str(AI_PIPELINE_ROOT) not in sys.path:
    sys.path.insert(0, str(AI_PIPELINE_ROOT))


def apply_corrections_to_split(
    dataset_path: Path,
    output_path: Path,
    split: str,
    corrections_file: Path,
) -> int:
    """Apply corrections to a single split. Returns number of corrections applied."""
    
    split_dir = dataset_path / split
    output_split_dir = output_path / split
    output_split_dir.mkdir(parents=True, exist_ok=True)
    
    # Load corrections
    corrections = np.load(corrections_file)
    indices = corrections['indices']
    new_labels = corrections['new_labels']
    
    print(f"  Corrections to apply: {len(indices):,}")
    
    # Create index -> new_label mapping
    correction_map = dict(zip(indices, new_labels))
    
    # Find and load labels
    labels_npy = split_dir / f"{split}_labels_labels.npy"
    files_npy = split_dir / f"{split}_labels_files.npy"
    
    if labels_npy.exists():
        # Numpy format
        print(f"  Loading labels from: {labels_npy}")
        labels = np.load(labels_npy)
        original_labels = labels.copy()
        
        # Apply corrections
        corrected_count = 0
        for idx, new_label in correction_map.items():
            if idx < len(labels):
                labels[idx] = new_label
                corrected_count += 1
        
        # Save corrected labels
        output_labels = output_split_dir / f"{split}_labels_labels.npy"
        np.save(output_labels, labels)
        print(f"  Saved corrected labels: {output_labels}")
        
        # Copy files array (unchanged)
        if files_npy.exists():
            output_files = output_split_dir / f"{split}_labels_files.npy"
            shutil.copy2(files_npy, output_files)
            print(f"  Copied files array: {output_files}")
        
        # Copy cache mapping (unchanged)
        cache_mapping = split_dir / "cache_mapping.npz"
        if cache_mapping.exists():
            shutil.copy2(cache_mapping, output_split_dir / "cache_mapping.npz")
            print(f"  Copied cache mapping")
        
        return corrected_count
    
    else:
        # JSON format
        labels_json = split_dir / "labels.json"
        if labels_json.exists():
            print(f"  Loading labels from: {labels_json}")
            with open(labels_json, 'r') as f:
                labels_data = json.load(f)
            
            # Apply corrections
            corrected_count = 0
            for idx, new_label in correction_map.items():
                if idx < len(labels_data):
                    labels_data[idx]['label'] = int(new_label)
                    corrected_count += 1
            
            # Save corrected labels
            output_labels = output_split_dir / "labels.json"
            with open(output_labels, 'w') as f:
                json.dump(labels_data, f)
            print(f"  Saved corrected labels: {output_labels}")
            
            return corrected_count
    
    print(f"  WARNING: No labels file found in {split_dir}")
    return 0


def main():
    parser = argparse.ArgumentParser(description="Apply label corrections")
    parser.add_argument("--corrections", type=Path, default=None,
                        help="Single corrections .npz file")
    parser.add_argument("--corrections-dir", type=Path, default=None,
                        help="Directory containing corrections for all splits")
    parser.add_argument("--dataset", type=Path, required=True)
    parser.add_argument("--split", choices=["train", "val"], default=None,
                        help="Single split to correct (use with --corrections)")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--min-confidence", type=float, default=0.0,
                        help="Only apply corrections above this confidence")
    args = parser.parse_args()
    
    if args.corrections is None and args.corrections_dir is None:
        parser.error("Either --corrections or --corrections-dir is required")
    
    args.output.mkdir(parents=True, exist_ok=True)
    
    # Copy components.json
    components_src = args.dataset / "components.json"
    if components_src.exists():
        shutil.copy2(components_src, args.output / "components.json")
        print(f"Copied components.json")
    
    total_corrected = 0
    
    if args.corrections is not None:
        # Single file mode
        if args.split is None:
            # Try to infer split from filename
            if "train" in args.corrections.name:
                args.split = "train"
            elif "val" in args.corrections.name:
                args.split = "val"
            else:
                parser.error("Cannot infer split from filename, please specify --split")
        
        print(f"\nProcessing {args.split}...")
        corrected = apply_corrections_to_split(
            args.dataset, args.output, args.split, args.corrections
        )
        total_corrected += corrected
        
        # Copy the other split unchanged
        other_split = "val" if args.split == "train" else "train"
        other_src = args.dataset / other_split
        other_dst = args.output / other_split
        if other_src.exists() and not other_dst.exists():
            print(f"\nCopying {other_split} unchanged...")
            shutil.copytree(other_src, other_dst)
    
    else:
        # Directory mode - process all splits
        for split in ["train", "val"]:
            corrections_file = args.corrections_dir / f"{split}_label_corrections.npz"
            if corrections_file.exists():
                print(f"\nProcessing {split}...")
                corrected = apply_corrections_to_split(
                    args.dataset, args.output, split, corrections_file
                )
                total_corrected += corrected
            else:
                # Copy unchanged
                src = args.dataset / split
                dst = args.output / split
                if src.exists() and not dst.exists():
                    print(f"\nCopying {split} unchanged (no corrections file)...")
                    shutil.copytree(src, dst)
    
    print(f"\n{'='*60}")
    print(f"COMPLETE")
    print(f"{'='*60}")
    print(f"Total corrections applied: {total_corrected:,}")
    print(f"Output dataset: {args.output}")
    print(f"\nNext: Retrain with the cleaned dataset:")
    print(f"  python train_classifier.py --dataset {args.output} ...")


if __name__ == "__main__":
    main()
